todo_app/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'todos/home', to: "todos#index"
  get 'todos/new' , to: "todos#new"
  post 'todos', to: "todos#create"
  get  'todos/:id'   , to: "todos#show", as: 'todo'
  get 'todos/:id/edit', to: "todos#edit", as: 'edit_todos'
  patch 'todos/:id', to: "todos#update"
  delete 'todos/:id', to: "todos#destroy"
  post 'todos/:id/complete' , to: "todos#complete" , as: 'complete_todo'
  get 'todo/list', to: "todos#list"

end

todo_app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

todo_app/app/models/todo.rb
class Todo < ApplicationRecord

    validates :description, presence: true
end

todo_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

todo_app/app/controllers/todos_controller.rb
class TodosController < ApplicationController
    before_action :set_todo, only: [:show, :edit, :update, :destroy, :complete]

def index

  @todos = Todo.all

end

def show
end

def edit
end

def new

  @todo = Todo.new

end

def update

 @todo.update(todo_params)
 redirect_to todos_home_path

end

def list

  @todos = Todo.all

end

def complete 

  @todo.update_attribute(:completed, true)
  redirect_to todos_home_path
end

def destroy
    @todo.destroy
    redirect_to todos_home_path
end

def create 

    
    @todo = Todo.new(todo_params)
    
    
    respond_to do |format|
        if @todo.save
          format.html { redirect_to todos_home_path, notice: 'ToDo List was successfully created.' }
          format.json { render :show, status: :created, location: @todo }
        else
          format.html { render :new }
          format.json { render json: @todo.errors, status: :unprocessable_entity }
        end
      end
end

def todo_params

    params.require(:todo).permit(:description,:completed)
end


def set_todo
  @todo = Todo.find(params[:id])
end

end

todo_app/app/helpers/application_helper.rb
module ApplicationHelper
end

todo_app/app/helpers/todos_helper.rb
module TodosHelper
end

todo_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>


  </head>

  <body>
 
     
    <%= yield %>
  </body>
</html>

todo_app/app/views/todos/edit.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Edit</title>
</head>
<body>
    
<h1>Edit</h1>

<%= form_with model: @todo, local: true  do |form| %>

<div class="field">
 <table>
<tr>
   <td> <%= form.label :description %> </td>
   <td> <%=form.text_area :description %></td>
</tr>
<tr>
   <td> <%= form.label :completed %> </td>
   <td> <%=form.check_box :completed %></td>
</tr>
 

 </table>

 </div>



<div class="actions">
    <%= form.submit %>
</div>
<% end %>
    
</body>
</html>

todo_app/app/views/todos/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>ToDo List</title>
</head>
<body>
    <h1>ToDo List </h1>

    <div class="well">
    <%= link_to 'Crear ToDo', todos_new_path %>
   
   <table class="table  table-dark table-hover">
    <thead>
      <tr>
        <th>Description</th>
        <th>Completed</th>
        <th> -  </th>
      </tr>
    </thead>

    <tbody>
      <% @todos.each do |todo| %>
        <tr>
          <td><%= todo.description %></td>
          <td> <%= check_box_tag 'completed_todo', 'yes', todo.completed  %> </td>
          <td> <%= button_to :completed, complete_todo_path(todo) %> </td>
          <td><%= link_to 'Show', todo, class: "btn btn-primary" %> <%= link_to 'Edit', edit_todos_path(todo), class: "btn btn-warning" %> <%= link_to 'Destroy', todo, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %></td>
        </tr>
      <% end %>

      <%= link_to "List" ,todo_list_path, class: "btn btn-primary" %>
    </tbody>
  </table>
</div>

    
</body>
</html>

todo_app/app/views/todos/list.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>List</title>
</head>
<body>
    
    <div class="container">
  <div class="row">
    <div class="col order-last">
   <h1> Lista de completados </h1>

     <table class="table  table-dark table-hover">
    <thead>
      <tr>
        <th>Description</th>
        <th>Completed</th>
        <th> -  </th>
      </tr>
    </thead>

    <tbody>
      <% @todos.each do |todo| %>
        <tr>
          <td><%= todo.description %></td>
          <td> <%= check_box_tag 'completed_todo', 'yes', todo.completed  %> </td>
          
          
        </tr>
      <% end %>

      
    </tbody>
  </table>
    </div>
    <div class="col">
     
    </div>
    <div class="col order-first">
    
    <h1> Lista de No completados </h1>
    <table class="table  table-dark table-hover">
    <thead>
      <tr>
        <th>Description</th>
        <th>Completed</th>
        <th> -  </th>
      </tr>
    </thead>

    <tbody>
      <% @todos.each do |todo| %>
        <tr>
          <td><%= todo.description %></td>
          <td> <%= check_box_tag 'completed_todo', 'yes', todo.completed  %> </td>
          
          
        </tr>
      <% end %>

      
    </tbody>
  </table>
    </div>
  </div>
</div>

    
</body>
</html>

todo_app/app/views/todos/new.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>New</title>
</head>
<body>
    
<h1>New</h1>


<%= form_with model: @todo, local: true  do |form| %>

<div class="field">
 <table>
  <tr>
   <td> <%= form.label :description %> </td>
   <td> <%=form.text_area :description %></td>
</tr>
<tr>
   <td> <%= form.label :completed %> </td>
   <td> <%=form.check_box :completed %></td>
   </tr>
 

 </table>

 </div>

<% if @todo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@todo.errors.count, "error") %> prohibited this todo from being saved:</h2>

      <ul>
      <% @todo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


<div class="actions">
    <%= form.submit %>
</div>
<% end %>
    
</body>
</html>

todo_app/app/views/todos/show.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Show</title>
</head>
<body>

     <div class="row">
        <div class="col-md-2"></div>
          <div class="col-md-8">
            <p>Description: <%= @todo.description %></p>
            <p>Completed:<%= @todo.completed %></p>
            <p>Creation:<%= time_ago_in_words @todo.created_at %></p>
             <%= link_to 'Edit', edit_todos_path(@todo), class: "btn btn-warning btn-sm" %> <%= link_to 'Back', todos_home_path, class: "btn btn-info btn-sm" %>
        </div>
      </div>

      
    
</body>
</html>